version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - ambulu_admin
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb+srv://miqdadyyy:monalisa123@node-1-lrxak.mongodb.net/pemro?retryWrites=true&w=majority
      MONGODB_DB: ambulu_admin
      JWT_SECRET: L2sa4K3d

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - ambulu_admin
    ports:
      - 8080:8080
    environment:
      API_URL: http://157.230.248.47:3000/

networks:
  ambulu_admin:
    driver: default
