version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: backend
    networks:
      - ambulu_admin
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      MONGODB_URL: mongodb+srv://miqdadyyy:monalisa123@node-1-lrxak.mongodb.net/pemro?retryWrites=true&w=majority
      MONGODB_DB: ambulu_admin
      JWT_SECRET: L2sa4K3d

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VUE_API_URL: http://ip172-18-0-25-bsn1qqlim9m000dldjl0-3000.direct.labs.play-with-docker.com/
    image: frontend
    networks:
      - ambulu_admin
    ports:
      - 80:80
    environment:
      API_URL: http://ip172-18-0-25-bsn1qqlim9m000dldjl0-3000.direct.labs.play-with-docker.com/

networks:
  ambulu_admin:
    driver: bridge
